BaseUrl = "http://blog.jonathanoliver.com/"
LanguageCode = "en-US"
Title = "Jonathan Oliver"
paginate = 10
DisqusShortname = "jonathanoliver"
Copyright = "(c) Jonathan Oliver. All rights reserved."
canonifyurls = true
theme = "casper"

[permaLinks] 
	post = "/:slug"

[params]
	description = "Eventually Consistent, Fully Distributed"
	cover = "images/cover.jpg"
	author = "Jonathan Oliver"
	authorlocation = "Utah, USA"
	authorwebsite = "https://blog.jonathanoliver.com"
	githubName = "joliver"
	twitterName = "jonathan_oliver"
	hideHUGOSupport = true
	hjsStyle = "default"

	[params.social]
		twitter = "jonathan_oliver"

[blackfriday]
	smartypants = false
	smartDashes = false